### ISSUE TITLE
async query when doing queries the "nice" way

### ISSUE THREAD

**Issue by unorthodoxgeek** [mariano/node-db-mysql#12]
I have this code (approximately)

this.query().
        update('users').
        set({ connected: true, nodeId: ths.user.clientId}).
        where('code = ?', [ currentName ]).
        execute(); //or execute(function(rows,cols){ some code })

and I need it to be executed asynchronously. the only way I found to work is that:

this.query.execute(this.query().
        update('users').
        set({ connected: true, nodeId: ths.user.clientId}).
        where('code = ?', [ currentName ]).sql(), //the query in plain text
        [], //values for the query - irrelevant since query's been parsed
        function(){}, //callback
        **{ async: false }**
);

which is extremely clumsy... is there a way to tell the first query to be asynchronous, and keep the clumsiness out?

**Comment by mariano** [comment]
What? I don't think I'm understanding you. By default all queries are executed asynchronously.If you set async to false, then the query executes _synchronously_.

Besides that i see several issues with your code (your "clumsy" way):
1. Why are you doing this.query.execute(this.query()) ?
2. Why are you setting [] for values? If you don't need values, just omit that argument.
3. Why are you specifying an empty function callback? If you don't need the callback, just leave it out.
4. If you don't have a callback, you are not making sure that your code executed successfully. What happens if the connection is lost?

So bottom line, if you want the code to execute _synchronously_ (which means it will block until the query is finished) you'd do:

```
var error;
this.query({ async: false }).
update('users').
set({ connected: true, nodeId: ths.user.clientId}).
where('code = ?', [ currentName ]).
execute(function(err, result) {
    error = err;
});

if (error) {
    console.log('QUERY ERROR: ' + error);
}
```

If you want to do it asynchronously, you'd do:

```
this.query().
update('users').
set({ connected: true, nodeId: ths.user.clientId}).
where('code = ?', [ currentName ]).
execute(function(err, result) {
    if (err) {
        return console.log('QUERY error: ' + error);
    }
});
```

**Comment by unorthodoxgeek** [comment]
yes, I did want to execute synchronously, What I do need is to execute the query with a callback function, but to keep it synchronous. as the first code you wrote in your reply doesn't work, that's exactly what I asked, how should I write the call?

as to what you wrote:
1. because this.execute doesn't work (whatever object which has the query method doesn't have the execute method
2. if I omit it, there will be an error, and I quote from your howto guide - the execute method takes four variables: execute([query], [values], [callback], [options])
3. like 2...
4. I meant to say that there might be a callback, my question was for queries in general, not this specific one.

to make it more clear:

```
this.query().
select('whatever').
execute(function(err, result){
code here;
},
{ async: false }
);
```

doesn't work, and I wish to understand how to do it right.
thanks :)

**Comment by mariano** [comment]
1. What do you mean the execute() method doesn't work? Ok, if you have a proper instance of Database, then its query() method returns an instance of Query. That instance has the execute() method. So to clear it up, you issue execute() on the Query instance.
2. The execute() method takes four arguments _at the most_. That's why the documentation includes them in brackets. So if you don't need the first three arguments, you can simply specify the fourth(options).

This code works perfectly (connection is done asynchronously, query is done synchronously). Obviously change the field names and conditions to work on your case:

```
new mysql.Database({
    hostname: 'localhost',
    user: 'root',
    password: 'password',
    database: 'db'
}).connect(function(err) {
    if (err) {
        return console.log('CONNECTION error: ' + err);
    }

    var error, result;

    this.query({ async: false }).
        update('users').
        set({ name: 'Lorna Doe' }).
        where('id = ?', [ 9999 ]).
        execute(function(err, res) {
            if (err) {
                error = err;
            } else {
                result = res;
            }
        });

    if (error) {
        console.log('QUERY ERROR: ' + error);
    } else {
        console.log('RESULT: ');
        console.log(result);
    }
});
```

You can also make it so even the connection is performed synchronously:

```
var db = new mysql.Database({
    hostname: 'localhost',
    user: 'root',
    password: 'password',
    database: 'db'
});

db.connect({ async: false });
if (!db.isConnected()) {
    return console.log("NOT CONNECTED");
}

var error, result;

db.query({ async: false }).
    update('users').
    set({ name: 'Lorna Doe' }).
    where('id = ?', [ 9999 ]).
    execute(function(err, res) {
        if (err) {
            error = err;
        } else {
            result = res;
        }
    });

if (error) {
    console.log('QUERY ERROR: ' + error);
} else {
    console.log('RESULT: ');
    console.log(result);
}

db.disconnect();
```

**Comment by unorthodoxgeek** [comment]
So to summarize, the { async: false } needs to be in the query method, not the execute method, this wasn't simple to understand from the documentation.
This one works well, thank you!

**Comment by mariano** [comment]
It doesn't _need_ to be, but it can be. I find it useful when you don't want to specify so many arguments.

I'm going to make it easy to specify execute(options, callback) as well in the next release

**Comment by mariano** [comment]
Bottom line it was complicated to do:

`execute(callback, options)`

So this is being fixed, and will be part of the next release. Thanks for reporting!

**Comment by mariano** [comment]
Ok as of db-mysql 0.6.1 you can do execute(callback, options), so the above example I've given can be rewritten as:

```
new mysql.Database({
    hostname: 'localhost',
    user: 'root',
    password: 'password',
    database: 'db'
}).connect(function(err) {
    if (err) {
        return console.log('CONNECTION error: ' + err);
    }

    var error, result;

    this.query().
        update('users').
        set({ name: 'Lorna Doe' }).
        where('id = ?', [ 9999 ]).
        execute(function(err, res) {
            if (err) {
                error = err;
            } else {
                result = res;
            }
        }, { async: false });

    if (error) {
        console.log('QUERY ERROR: ' + error);
    } else {
        console.log('RESULT: ');
        console.log(result);
    }
});
```

You can view the [Release announcement](http://nodejsdb.org/2011/05/node-db-0-6-1-released/) and upgrade db-mysql
