### ISSUE TITLE
incorrect BLOB charset

### ISSUE THREAD

**Issue by taai** [mariano/node-db-mysql#28]
When a BLOB is selected, it is not converted to Buffer correctly.

Oh, actually this is a problem in node-db module, not in node-db-mysql.

For example, this is correct:
<Buffer 15 03 00 02 00 97 15 05 00 03 35 32 33>

This is what is now wrong:
<Buffer 15 03 00 02 00 ef bf bd 15 05 00 03 35 32 33>

My guess is that BLOB is getting converted to Buffer without second argument which by default is 'utf8', but it should be 'binary' for BLOB's.
I don't know C++, but this is how I would do it in JavaScript:

``` javascript
value = new Buffer( BLOB_value_here , 'binary' );
```

I think that this is the code which should get updated, I found it in 'query.cc' file, line 1308:

``` c++
value = v8::Local<v8::Value>::New(node::Buffer::New(v8::String::New(currentValue, currentLength)));
```

As I don't know C++, I can only guess how the fix would look like:

``` c++
value = v8::Local<v8::Value>::New(node::Buffer::New(v8::String::New(currentValue, currentLength), 'binary' ));
```

I hope you will fix this soon.
Thank you for the great job you are doing!

**Comment by mariano** [comment]
I'm sorry, but that's wrong. In C++ land, there's no way to define the initial encoding of the Buffer as it is just that, a continuous buffer of raw bytes.

From JS land, you can convert that buffer back to any encoding you want, for example:

``` javascript
myBuffer.toString('binary');
```

In C++ land these are the constructors:

https://github.com/joyent/node/blob/master/src/node_buffer.h#L93

Now on JS land I do se the encoding, but in essence it's only used to calculate the length when one's not provided. I did attempt to issue a call to this constructor, and frankly setting different encodings made no difference, since I'm already providing the length.

If the toString() method does not solve it for you, could you please provide me with an INSERT SQL statement I can use to replicate your data?

**Comment by roncli** [comment]
While taai's solution is incorrect, the problem is quite real.  Once that "0x97" byte is converted to the Unicode Replacement Character "0xEFBFBD", the information is lost and cannot be recovered by any amount of converting.

Therefore, we need to create the Buffer without converting the data to string first.

[edit]
This is a problem with node-db, as outlined in https://github.com/mariano/node-db/issues/11.  That solution should fix the problem.
[/edit]
