### ISSUE TITLE
Error in Quick Start Guide.

### ISSUE THREAD

**Issue by geekinthesticks** [mariano/node-db-mysql#99]
Shouldn't:

```
var mysql = require('db-mysql');
```

be

```
var mysql = require('node-db-mysql');
```

**Comment by raadad** [comment]
If you were to install this via the npm registry, it gets names as db-mysql in your node_modules folder, because of the advice I gave you previously, it created the folder names node-db-mysql.

you can rename it back to db-mysql in your node-modules, if you want things to "just work" when this package is updated

Hope that helps.

**Comment by geekinthesticks** [comment]
Thanks for the explanation. Time to read a few more man pages:)
